### ISSUE TITLE
Is it possible to analyze pdf images instead of png/jpgs?

### ISSUE THREAD

**Issue by georgerabus** [lucianotonet/groq-laravel#2]
I want to use VIsioan API but it looks like only images are allowed.

**Comment by lucianotonet** [comment]
Unfortunately this is not possible directly with the vision model (LLaVA V1.5 7B) available today on Groq.
If your PDF contains only images you can create a PDF to PNG/JPEG conversion layer and then bind the converted image, but this needs to be done manually.
